version: "3.4"
services:
  rabbitmq:
    user: "999"
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - '5672:5672'
      - '15672:15672'
  timeline-service:
    image: timelineservice
    build:
      context: .
      dockerfile: ./projects/TimelineService/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      rabbitmq:
        condition: service_healthy